GET  http://localhost:8001/todos/?status=DONE&priority=MEDIUM


###

POST http://localhost:8001/todos/
Content-Type: application/json

    
   {
    "id": 2,
    "todo": "Buy a Car",
    "priority": "MEDIUM",
    "status": "TO DO",
    "category": "HOME",
    "dueDate": "2020-09-22"
  }

###

PUT http://localhost:8001/todos/1/
Content-Type: application/json

{    
    
    "dueDate":"2003-06-06"
    
}

###
GET http://localhost:8001/agenda/?date=2021-01-12

### 
DELETE http://localhost:8001/todos/2
